### ISSUE TITLE
No default case in switch statement

### ISSUE THREAD

**Issue by rowan04** [william-Cross12/University-folder#2]
https://github.com/william-Cross12/University-folder/blob/6e0884ce498710723166af9bf2adb1552a28efec/module_1_programming_concepts/week_2/Exercise_2.java#L18-L19

No default case in switch statement - will cause errors if unexpected inputs passed.

**Comment by Will-Cross1** [comment]
not as long as the user uses correctly

**Comment by rowan04** [comment]
i need to speak to your manager about this, not good enough

**Comment by rowan04** [comment]
this is a serious issue
